### ISSUE TITLE
Adding notebook to Mercury is failing - no kernels available

### ISSUE THREAD

**Issue by NATabbal** [mljar/mercury#175] opened 2022-10-23 18:53 UTC
Hello, 

I am trying to add my python notebooks to mercury and I am getting the following message: 

"Your notebook kernel name is set to 'python3'.
In this system available kernels are [].
Sorry, cant automatically update the kernel name in the notebook."

Any solution to this ? 

Thank you

Nadim

**Comment by pplonski** [comment] 2022-10-24 10:39
Hi @NATabbal,

thank you for reporting the issue. 

The error suggests that you have no Python kernels available. What operating system are you using?

What output do you get after running:

```
jupyter kernelspec list
```

**Comment by NATabbal** [comment] 2022-10-24 12:31
The output is the following:

Available kernels:  
python 3 C:\Users\Nadim Tabbal etc...(This is the address where it is locally saved)

**Comment by pplonski** [comment] 2022-10-24 12:37
@NATabbal output is correct. It should work. Can you try once again?

What output do you get when you run:

```
mercury demo
```

**Comment by DavidJOV** [comment] 2022-10-24 13:19
Hi @NATabbal,

I had the same problem when using the DataSpell IDE, when creating a new notebook directly through the Jupyter browser interface, everything worked fine .

**Comment by NATabbal** [comment] 2022-10-24 17:57
when I run it I could view the demo on 127.0.0.1:8000. It is there uploaded. I can't though upload my notebooks

**Comment by pplonski** [comment] 2022-10-24 18:49
There must be some bug in Mercury. Could you please upload demo notebook to GitHub? After running demo the demo.ipynb file should be created. It should have meta data set in it. Im wondering what kernel name is set there.

After running kernelspec command you got `python 3` or `python3`? Do you have space in it? Maybe thats the problem?

**Comment by NATabbal** [comment] 2022-10-25 06:25
I got python3 (without space). Do you mean the demo file that is provided by mercury or my notebook?

**Comment by pplonski** [comment] 2022-10-25 08:23
I mean demo provided by Mercury. But if you can send yours then it would be great.

**Comment by NATabbal** [comment] 2022-10-31 07:27
Dear Piotr,

Sorry for the delay in my reply. I ran in my anaconda prompt    mercury run demo   
Then I opened http://127.0.0.1:8000. The demo was uploaded and its URL is http://127.0.0.1:8000/app/1

I had installed pip install mljar-mercury . It might be your demo actually.

It is only when I upload my notebook that it doesn't get uploaded. 

Am I getting you right?

**Comment by pplonski** [comment] 2022-11-02 07:48
What have you tried to run your notebook? Have you tried `mercury run` in the notebook directory? Could you please upload your notebook to GitHub?

**Comment by NATabbal** [comment] 2022-11-06 18:25
Hello, 
I am unable to upload the python 3 file as github is saying that it does not support this type of files upload. I tried to zip it and it did not work either. Any suggestion?

**Comment by pplonski** [comment] 2022-11-07 09:04
You can create an example repository and upload files there. You can create a gist with files. You can just copy and paste all code and paste it in the comment start with triple backquote and end code piece with triple backquote.

**Comment by JerWer** [comment] 2022-11-24 03:16
Hi,
I have same issue. what was the solution to this problem please?

**Comment by JerWer** [comment] 2022-11-25 08:37
Hi,
really same story as for NATabbal:
"jupyter kernelspec list" returns:
python3 c:\users\...\jupyter\kernels\python3

the demo works: if ask "mercury run demo", it gets me "Starting development server at http://127.0.0.1:8000/"
but if asks "mercury run myfile", it gets me the same thing: links to the demo page. 

I am trying to reproduce the example on this webpage: https://mljar.com/blog/dashboard-python-jupyter-notebook/

**Comment by pplonski** [comment] 2022-11-25 09:31
Thank you @JerWer,

Please send me the exact output from `jupyter kernelspec list`, maybe there is a bug in parsing?

My exact output is:
```
Available kernels:
  cvenv          /home/piotr/.local/share/jupyter/kernels/cvenv
  dashenv        /home/piotr/.local/share/jupyter/kernels/dashenv
  demo_env       /home/piotr/.local/share/jupyter/kernels/demo_env
  python3        /home/piotr/.local/share/jupyter/kernels/python3
```

**Comment by JerWer** [comment] 2022-11-28 02:21
Hi,
again my output is:

Available kernels:
  python3    c:\users\serjw\...\demo_env\share\jupyter\kernels\python3

**Comment by nagatushar** [comment] 2022-12-23 21:43
So I have a silly comment.

I have this issue too on one of my computers.

on this computer I made the grave mistake of having "Name LastName" in my user path rather than "name.lastname" or "name_lastname"

It seems the OP of this thread also has a space in their file path.

Is this breaking jupyter finding the python3 kernel?

**Comment by nagatushar** [comment] 2022-12-24 21:56
https://codeburst.io/changing-a-profile-name-in-windows-9da6c02234e4

I changed my username to not have a space in windows.

WARNING: This is something you do at your own risk

this did fix my issue with the kernel-related thing.

I vetted this because my work PC does not have a space in the user name so this is perhaps one reason for this issue.

**Comment by pplonski** [comment] 2023-02-15 11:41
Hi @NATabbal, @JerWer, @nagatushar,

I'm closing this issue. We released Mercury V2 this week. The new version is not checking kernels. You can read more at https://RunMercury.com

**Closed by pplonski** 2023-02-15 11:41 UTC
Labels: bug
