### ISSUE TITLE
mercury.exe instead of mercury 

### ISSUE THREAD

**Issue by shivendra2015iiit** [mljar/mercury#35] opened 2022-02-06 22:25 UTC
During:
 mercury watch <notebook address>

c:\programdata\anaconda3\python.exe: can't open file 'C:\Users\<username>\AppData\Roaming\Python\Python38\Scripts\mercury': [Errno 2] No such file or directory

instead mercury it should look for mercury.exe

I have to copy paste mercury.exe and rename it to mercury to make it work

![image](https://user-images.githubusercontent.com/19734489/152704047-466c9058-1604-4cbf-9983-693e5e1ff535.png)

temporary fix:
![image](https://user-images.githubusercontent.com/19734489/152704070-8a1b04ee-3e07-403c-be78-0537d2ea4187.png)

**Comment by pplonski** [comment] 2022-02-07 08:38
Hi @shivendra2015iiit, 

Thank you for reporting the issue. Some other users have similar problems but looks like you found the reason. I will try to catch some windows laptop this week and fix this. Thank you again!

**Comment by tariqrahiman** [comment] 2022-02-07 19:30
@pplonski  I got the same error and this is what I reported. Waiting for the patch. Thanks @shivendra2015iiit Naatil evedeya? :-)

**Comment by pplonski** [comment] 2022-02-10 09:40
Thanks @aplonska for sharing the windows laptop - I'm able to reproduce the error. Working on fix.

**Comment by pplonski** [comment] 2022-02-10 10:30
@tariqrahiman @shivendra2015iiit it is fixed. The new version will be released soon (probably tomorrow). I will let you know. Thank you for help with finding this issue 👍

**Closed by pplonski** 2022-02-10 10:30 UTC
Labels: bug

**Comment by pplonski** [comment] 2022-02-10 12:24
@tariqrahiman @shivendra2015iiit the new version is released (0.4.0). Please run `pip install -U mljar-mercury` to update the framework.

**Comment by shivendra2015iiit** [comment] 2022-02-10 15:12
Thanks @pplonski  I recently hosted my notebook in local lan to access from other computers in same network, if you want I can help you with the documention which can be added in wiki. shivam9935@gmail.com

**Comment by pplonski** [comment] 2022-02-10 15:18
@shivendra2015iiit sure, if you have some ideas what can be added to wiki please add issue. You can add issue with ready documentation - I will review and paste into the wiki.

I think it might be useful for users to add YouTube videos with examples how to start.

Thank you!
