### ISSUE TITLE
Date widget

### ISSUE THREAD

**Issue by kapily** [mljar/mercury#286] opened 2023-05-21 04:15 UTC
Could you add a "date" widget? I'm currently using the text widget to enter `yyyy-mm-dd`, but an actual date picker would be really convenient. Even better if there are ways to select -7d, -14d, etc. via the widget

**Comment by pplonski** [comment] 2023-05-22 11:01
We will add date widget - here is issue for date and time picker #10

**Comment by pplonski** [comment] 2023-05-23 09:55
Closing as a duplicate of #10.

**Closed** 2023-05-23 09:55 UTC
Labels: enhancement, help wanted
