### ISSUE TITLE
Notebooks' persistence

### ISSUE THREAD

**Issue by gmouawad** [mljar/mercury#311] opened 2023-06-06 13:59 UTC
I added two notebooks under /app/mercury directory and execute mercury run.
The two notebooks were displayed on Mercury front end and still showing.

Then, I was trying to add a new notebook in that directory and saw that the two ipynb files disappeared.
Is this a bug or do we have a persistence issue?

Note that we have mercury installed based on the below link:
https://runmercury.com/docs/docker-compose/

**Comment by pplonski** [comment] 2023-06-06 14:04
Thank you @gmouawad for reporting the issue. Are you still able to execute previous notebooks? Are you able to view them after clicking on notebook title?

**Comment by gmouawad** [comment] 2023-06-06 14:13
Hello @pplonski well the notebook opens but it not rendering and I am getting two red icons:
WebSocket: Disconnected
and
Worker: Unknown

**Comment by pplonski** [comment] 2023-06-06 14:44
Are you able to repeat this scenario with your deployment?

**Comment by pplonski** [comment] 2023-06-06 14:49
Please try to start with fresh deployment (remove database and all notebooks) and try to reproduce the issue.

**Comment by akarataev** [comment] 2023-06-06 20:03
Hi guys!

I have a similar problem, even on the demo app. Installed according to instructions for docker compose. 

I can give access or provide any necessary information 😐


https://github.com/mljar/mercury/assets/35783149/94da8a0e-7922-4c24-82ed-be487d473f1f

**Comment by pplonski** [comment] 2023-06-07 06:20
Thank you @akarataev for reporting the issue and for video. Do you have the same problem when have public Site?

**Comment by akarataev** [comment] 2023-06-07 08:47
@pplonski 

Hello!

Removed private dashboards, left only the demo and made the site public. 
You can go to the site and see if it helps somehow 

https://mercury.transience.team

**Comment by pplonski** [comment] 2023-06-07 09:16
Thank you! Looks like some bug. Because you can send REST requests to the server, but cant connect with WebSocket. I will debug it.

**Comment by pplonski** [comment] 2023-06-07 09:41
@akarataev may I ask you, how have you found Mercury? We have in the last few days a huge traffic peak, and we can't locate it.

One more question, could you please tell me more about your use case? Did you successfully manage to build locally app with Mercury? 

Thank you!

**Comment by akarataev** [comment] 2023-06-07 10:27
@pplonski 

Yes, sure!

We were looking for some convenient solution to share jupiter notebooks with analytics for a mobile application. Our analyst deployed Mercury locally, adapted several notebooks and showed how it works.

And it was great! The ability to create interactive applications in a couple of minutes based on notebooks is amazing, it opens up a lot of opportunities for quickly demonstrating the results of arbitrarily complex data processing 😍

I really hope that you can quickly cure all children's sores, because the product that you make is really of great value. Classic systems for working with data like ga, amplitude, etc. simply cannot be as flexible as a notebook can be.

Returning to our problem, I noticed that the port 9000 that you use in the configuration for the nginx does not appear in the created containers (see screenshots). I'm not sure if this is really the problem, but just in case I decided to show you.

<img width="1318" alt="Screenshot 2023-06-07 at 12 51 42" src="https://github.com/mljar/mercury/assets/35783149/11fc5b77-e0e5-4617-9f8b-974a4391b8d7">
<img width="932" alt="Screenshot 2023-06-07 at 12 52 46" src="https://github.com/mljar/mercury/assets/35783149/5f3dcf08-5e8b-4f02-9d84-b1f227c09d6d">

**Comment by pplonski** [comment] 2023-06-07 10:30
Thank you!

Ports `8000` and `9000` are used by containers internally. Only ports `80` and `443` are open to world. I'm pretty sure that some configuration is missing in the docs, and that's why the problem.

**Comment by tori3852** [comment] 2023-06-07 11:23
> We have in the last few days a huge traffic peak, and we can't locate it.

Mercury was mentioned in 2023-06-06 [TLDR](https://tldr.tech)'s newsletter: 

> Mercury (GitHub Repo)
>
> Mercury allows users to build web apps in Jupyter Notebooks using only Python. It enables users to add interactive widgets in Python notebooks so they can share results without rewriting notebooks to web frameworks. Mercury can be used to create interactive presentations, build data-rich dashboards, create reports, and more.

**Comment by gmouawad** [comment] 2023-06-08 14:46
> Please try to start with fresh deployment (remove database and all notebooks) and try to reproduce the issue.

dear @pplonski we tried to redo the configuration but the https is not working due to an error from nginx docker container:


023/06/08 13:58:09 [emerg] 17#17: cannot load certificate "/etc/letsencrypt/live/mercury01.srvdoc01.infrae2g.com/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/mercury01.srvdoc01.infrae2g.com/fullchain.pem, r) error:10000080:BIO routines::no such file)
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/mercury01.srvdoc01.infrae2g.com/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/mercury01.srvdoc01.infrae2g.com/fullchain.pem, r) error:10000080:BIO routines::no such file)

**Comment by pplonski** [comment] 2023-06-09 07:34
Hi @gmouawad,

Did you setup DNS correctly before running setup-https.sh script? What was the output from setup-https.sh?

**Comment by gmouawad** [comment] 2023-06-09 09:01
> Hi @gmouawad,
> 
> Did you setup DNS correctly before running setup-https.sh script? What was the output from setup-https.sh?
> 
> Maybe it is worth to create a new issue for problems with SSL certificates?

okay, I will do it. Meanwhile, I asked my colleague who is creating the containers and working with this issue. I'll let you once he answered your question.

**Comment by akarataev** [comment] 2023-06-12 09:53
Hello guys!

Any news on the possibility of installing the self-hosted mercury?

**Comment by pplonski** [comment] 2023-06-12 12:02
Hi @akarataev,

I'm working on this. I would like to improve docs as well.

**Comment by pplonski** [comment] 2023-06-12 16:52
Hi @gmouawad, @akarataev 

I've found the issue. There is missing proxy for websockets in nginx configuration for HTTPS deployments.

The fix and new docs should be ready tomorrow.

**Comment by pplonski** [comment] 2023-06-12 17:07
The updated code is in the repo - you can try do pull newest version and rebuild docker, should be working. I will update docs tomorrow.

**Comment by gmouawad** [comment] 2023-06-12 17:55
> Hi @gmouawad, @akarataev
> 
> I've found the issue. There is missing proxy for websockets in nginx configuration for HTTPS deployments.
> 
> The fix and new docs should be ready tomorrow.

awesome thanks @pplonski

**Comment by akarataev** [comment] 2023-06-12 18:28
@pplonski this is great news! Thank you for doing this! I'm going to wait for the documentation and be sure to write tomorrow how it went.

**Comment by pplonski** [comment] 2023-06-13 10:15
@gmouawad @akarataev docs updated https://runmercury.com/docs/docker-compose/ - you might need to refresh the website with Ctrl+F5

I'm closing the issue. If you will still have problems please feel free to reopen. 

Thank you for your help!

**Closed by pplonski** 2023-06-13 10:15 UTC

**Comment by gmouawad** [comment] 2023-06-13 11:22
> The updated code is in the repo - you can try do pull newest version and rebuild docker, should be working. I will update docs tomorrow.

The updated version worked like a charm, my colleague and I thank you a lot.
