### ISSUE TITLE
Better error message when Jupyter not detected

### ISSUE THREAD

**Issue by x18-1** [mljar/mercury#184] opened 2022-12-05 10:50 UTC
this is the error:
```
Error during notebook initialization. [WinError 2] 系统找不到指定的文件（No such file）
```

The path don't have probelms,I have try many times , but it didn't work。

**Comment by pplonski** [comment] 2022-12-05 10:55
hi @x18-1,

Thanks for submitting the issue. Please provide more details so I can reproduce the problem locally. 
- What command are you using to start mercury? Have you tried the `mercury demo` command?
- Could you please provide a full terminal printout with the error message?

**Comment by pplonski** [comment] 2022-12-05 13:36
hmm, could you please attach `demo.ipynb` notebook that is generated by Mercury

**Comment by x18-1** [comment] 2022-12-05 13:51
this is file directory:
<img src = 'https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/9147/image-20221205214913429.png'>
<img src = 'https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/9147/image-20221205215010946.png'>

this is terminal printout:
```
PS D:\code\test> cd demo
PS D:\code\test\demo> mercury run demo

     _ __ ___   ___ _ __ ___ _   _ _ __ _   _ 
    | '_ ` _ \ / _ \ '__/ __| | | | '__| | | |
    | | | | | |  __/ | | (__| |_| | |  | |_| |
    |_| |_| |_|\___|_|  \___|\__,_|_|   \__, |
                                         __/ |
                                        |___/ 
        
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_drf_filepond, notebooks, sessions, tasks
Running migrations:
  No migrations to apply.

0 static files copied to 'E:\python\Lib\site-packages\mercury\static', 199 unmodified.
Initialize demo.ipynb
Error during notebook initialization. [WinError 2] 系统找不到指定的文件。
Successfully added a notebook (id:None)
Performing system checks...

System check identified no issues (0 silenced).
December 05, 2022 - 21:48:49
Django version 3.2.5, using settings 'server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
celery beat v5.1.2 (sun-harmonics) is starting.
__    -    ... __   -        _
LocalTime -> 2022-12-05 21:48:51
Configuration ->
    . broker -> sqla+sqlite:///celery.sqlite
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%ERROR
    . maxinterval -> 1.00 minute (60s)

 -------------- celery@DESKTOP-GKT9HQD v5.1.2 (sun-harmonics)
--- ***** -----
-- ******* ---- Windows-10-10.0.19041-SP0 2022-12-05 21:48:51
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         server:0x17b70c954f0
- ** ---------- .> transport:   sqla+sqlite:///celery.sqlite
- ** ---------- .> results:     sqlite:///celery.sqlite
- *** --- * --- .> concurrency: 1 (gevent)
-- ******* ---- .> task events: ON
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


[05/Dec/2022 21:49:17] "GET / HTTP/1.1" 200 2246
[05/Dec/2022 21:49:17] "GET /static/css/main.10b25b9c.chunk.css HTTP/1.1" 200 2564
[05/Dec/2022 21:49:17] "GET /static/css/2.c6cf5ff9.chunk.css HTTP/1.1" 200 229115
[05/Dec/2022 21:49:17] "GET /static/js/main.f5e216e0.chunk.js HTTP/1.1" 200 54893
[05/Dec/2022 21:49:17] "GET /static/js/2.6e058ab1.chunk.js HTTP/1.1" 200 1242134
[05/Dec/2022 21:49:17] "GET /static/mercury_logo.svg HTTP/1.1" 200 42362
[05/Dec/2022 21:49:17] "GET /api/v1/version/ HTTP/1.1" 200 15
[05/Dec/2022 21:49:17] "GET /api/v1/welcome/ HTTP/1.1" 200 10
[05/Dec/2022 21:49:17] "GET /api/v1/notebooks/ HTTP/1.1" 200 2
[05/Dec/2022 21:49:17] "GET /static/favicon.ico HTTP/1.1" 200 15406
[05/Dec/2022 21:49:18] "GET /static/manifest.json HTTP/1.1" 200 324
```

**Comment by pplonski** [comment] 2022-12-05 14:03
1. Could you please send me text representation of notebook. When you open the notebook with text editor, you should get JSON. Please send it. I would like to check the metadata there.
2. Looks like you have Mercury installed in `E` drive, and your demo is in `D` drive. Please try to run demo in `E` drive. Maybe that's the issue?

**Comment by x18-1** [comment] 2022-12-05 14:28
Thanks@pplonski
 
i have solve the problem,The reason is that I didn't put jupyter to the environment path(my vscode can use jupyter but my pycharm can't use).
After i add jupyter to environment path,my pycharm can use jupyter-notebook and `mercury run demo`  is right work

**Comment by pplonski** [comment] 2022-12-05 14:36
@x18-1 great!!!

I'm not closing the issue. There should be a better error message. Sorry for the problem.

May I ask what are you building with Mercury? BTW, I'm working on Mercury V2, it should be faster, and will have caching and dynamic widgets.

**Comment by pplonski** [comment] 2023-02-15 11:43
I'm closing the issue. You can also check Mercury V2 and read more about it on https://RunMercury.com

We moved from YAML to Python API.

**Closed by pplonski** 2023-02-15 11:43 UTC
